apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-webserver
  labels:
    app: nginx-webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-webserver
  template:
    metadata:
      labels:
        app: nginx-webserver
    spec:
      containers:
      - name: nginx
        image: nginx:stable-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: nginx-default-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        - name: www-data
          mountPath: /var/www/html
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: nginx-default-config
        configMap:
          name: nginx-default-config
      - name: www-data
        emptyDir: {}